<?php

namespace ContainerVIV2Uox;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Bkb9uesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Bkb9ues' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Bkb9ues'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'user' => ['privates', '.errored..service_locator.Bkb9ues.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.Bkb9ues": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'userPasswordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'em' => '?',
            'user' => 'App\\Entity\\User',
            'userPasswordHasher' => '?',
        ]);
    }
}
