<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMit6QS2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMit6QS2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMit6QS2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMit6QS2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMit6QS2\App_KernelDevDebugContainer([
    'container.build_hash' => 'Mit6QS2',
    'container.build_id' => '5c6cb49d',
    'container.build_time' => 1685379692,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMit6QS2');
